import type { Metadata } from "next";
import { Anton, Inter } from "next/font/google";
import "./globals.css";


const anton = Anton({
  weight: "400",
  variable: "--font-anton",
  subsets: ["latin"],
});

const inter = Inter({
  weight: "400",
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "McLaren",
  description: "Generated by Himanshu",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${anton.variable} ${inter.variable} relative`}
      >
        {children}
      </body>
    </html>
  );
}
